### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by sandhawalia**
This PR address (partially). 

1. https://github.com/NVIDIA/VideoProcessingFramework/issues/216
2. https://github.com/NVIDIA/VideoProcessingFramework/pull/357
3. https://github.com/NVIDIA/VideoProcessingFramework/issues/355
4. https://github.com/NVIDIA/VideoProcessingFramework/issues/162
5. https://github.com/NVIDIA/VideoProcessingFramework/issues/343

Following packages are updated/deleted. ReadMe.md updated.

1. Update `Poetry==1.1.13`
2. Removed `nvidia-pyindex`, `nvidia-tensrorrt` (see [comment](https://github.com/NVIDIA/VideoProcessingFramework/pull/357#issuecomment-1195931657))
3. Use latest `ffmpeg` container from [docker-hub](https://hub.docker.com/r/jrottenberg/ffmpeg) instead of building `ffmpeg` sources
6. Option to disable installing `torch` for `vpf-tensorrt` (see [comment](https://github.com/NVIDIA/VideoProcessingFramework/pull/357#issuecomment-1192466937)) with `GEN_PYTORCH_EXT=0`
7. Tested with `Video_Codec_SDK 11.1`

## Test this PR

```
# Get the repo
git clone git@github.com:yaak-ai/VideoProcessingFramework.git -b docker-updates-07-08-2022
# Get test sample
wget http://www.scikit-video.org/stable/_static/bikes.mp4 -P $HOME/Downloads/
```

### VPF
```
docker-compose -f docker/docker-compose.yml build vpf
docker-compose -f docker/docker-compose.yml run -v $HOME/Downloads:/Downloads vpf
python SampleDecode.py -g 0 -e /Downloads/bikes.mp4 -r /Downloads/bikes-vpf.mp4
```

### PyTorch  ext.
```
docker-compose -f docker/docker-compose.yml build --build-arg GEN_PYTORCH_EXT=1 vpf
docker-compose -f docker/docker-compose.yml run -v $HOME/Downloads:/Downloads vpf
python SampleTorchResnet.py 0 /Downloads/bikes.mp4
```

### OpenGL ext.
```
docker-compose -f docker/docker-compose.yml build --build-arg GEN_OPENGL_EXT=1 vpf
docker-compose -f docker/docker-compose.yml run -v $HOME/Downloads:/Downloads vpf
python SampleOpenGL.py --gpu-id 0 --encoded-file-path /Downloads/bikes.mp4
```

### TensorRT ext.
```
docker-compose -f docker/docker-compose.yml build --build-arg GEN_PYTORCH_EXT=1 vpf-tensorrt
docker-compose -f docker/docker-compose.yml run -v $HOME/Downloads:/Downloads vpf-tensorrt
python SampleTensorRTResnet.py 0 /Downloads/bikes.mp4
```

## Container sizes
```
# Barebone
nvidia/videoprocessingframework   vpf                    69533d5c5c96   8 seconds ago   4.81GB
# GEN_PYTORCH_EXT=0
nvidia/videoprocessingframework   vpf-tensorrt           d0b1902dac09   4 minutes ago   7.58GB
```

cc @gedoensmax

### CODE REVIEW

**Comment by rarzumanyan** [comment]
Hi @sandhawalia 

How does this PR relates to #357?

**Comment by sandhawalia** [comment]
Hey @rarzumanyan. While reviewing #357 I found other issues f.ex #216 and #162 which were related . Reviewing #357 I realized changes needed to `Makefile` and compose pipeline which is shared across images needed an overhaul to fix `docker-compose` for all images (barebone vpf, pytorch and tensorrt) including the one outlined in #357 

This PR is a superset to #357. Happy to tag @gedoensmax as a co-contributor.

**Comment by gedoensmax** [comment]
If you want to take this on feel free! No need to tag me :)

**Review by rarzumanyan — APPROVED** [review]
LGTM

**Comment by rarzumanyan** [comment]
Merging with feature branch `pr_368` for further testing.
Will merge with `master` a bit later.

**Pull request merged**
