### PR TITLE
[WIP] Barebone VPF + PyTorch extension docker image build (#294)

### PR DESCRIPTION
**Pull request by rarzumanyan**
* virtual env build

* Cmake list updates

* vpf + torch working

* newline

* formatting

### CODE REVIEW

**Comment by rarzumanyan** [comment]
Adding @sandhawalia for visibility, linking issue.

**Comment by sandhawalia** [comment]
```
ERROR: Permission to NVIDIA/VideoProcessingFramework.git denied to sandhawalia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

👋🏽 it would seem i cannot push to `pr_294`

**Comment by rarzumanyan** [comment]
Hi @sandhawalia 

I can’t give you a direct access to branch because repository is managed by my organisation, not just me.

Please create a PR against ‘pr_294’ branch, I’ll merge it.

**Comment by sandhawalia** [comment]
https://github.com/NVIDIA/VideoProcessingFramework/pull/296

**Comment by sandhawalia** [comment]
This is ready to be tested. Instructions in here https://github.com/NVIDIA/VideoProcessingFramework/pull/296#issue-1082049546

**Comment by rarzumanyan** [comment]
Great news, thank you.
Let's wait for @NNsauce to test it. If it goes fine, I'll merge feature branch to `master`.

**Comment by rarzumanyan** [comment]
No updates from issue originator, considering this fixed and merging to main branch to avoid divergence.

**Pull request merged**
