### PR TITLE
Pybind via CMake (#361)

### PR DESCRIPTION
**Pull request by rarzumanyan**
* Delete pybind11 from manual source inclusion.

* Import a newer version of pybind 11 via CMake directly

* Fix build issue with latest pybind.

* Should allow for building the pytorch extensions

### CODE REVIEW

**Comment by rarzumanyan** [comment]
@jakepoz 

I was able to successfully build the VPF from `pr_361` feature branch but tests fail:
```bash
roman@G7:~/Git/VideoProcessingFramework/install/bin$ python3 ./test_PyNvDecoder.py
...................corrupted size vs. prev_size
Aborted (core dumped)
roman@G7:~/Git/VideoProcessingFramework/install/bin$ python3 ./test_PyNvDecoder.py
....................free(): invalid pointer
Aborted (core dumped)
roman@G7:~/Git/VideoProcessingFramework/install/bin$ python3 ./test_PySurface.py
.realloc(): invalid pointer
Aborted (core dumped)
```

Please make sure that PR is passing tests before we can merge to `master`.

**Comment by jakepoz** [comment]
Hi, I have done a clean checkout and build, and the tests pass for me (except for PySurface but that's only because I haven't installed pycuda). I am on Ubuntu 22.04, NVIDIA 1080 card, Driver Version: 515.65.01    CUDA Version: 11.7, Python 3.9, Pytorch 1.12.

**Comment by rarzumanyan** [comment]
Hi @jakepoz 

>the tests pass for me (except for PySurface)

Please install the pycuda and run `test_PySurface.py`, I can't accept PR if some tests are failing or not checked.

**Comment by jakepoz** [comment]
```
(vpf) jake@jake-Office:~/VideoProcessingFramework/install/bin$ python test_PyNvDecoder.py 
.....................
----------------------------------------------------------------------
Ran 21 tests in 4.906s

OK
(vpf) jake@jake-Office:~/VideoProcessingFramework/install/bin$ python test_PyNvEncoder.py 
..
----------------------------------------------------------------------
Ran 2 tests in 0.231s

OK
(vpf) jake@jake-Office:~/VideoProcessingFramework/install/bin$ python test_PyFfmpegDemuxer.py 
..............
----------------------------------------------------------------------
Ran 14 tests in 0.004s

OK
(vpf) jake@jake-Office:~/VideoProcessingFramework/install/bin$ python test_PySurface.py 
...
----------------------------------------------------------------------
Ran 3 tests in 0.917s

OK
(vpf) jake@jake-Office:~/VideoProcessingFramework/install/bin$ 
```

**Comment by rarzumanyan** [comment]
@jakepoz 

Thanks a lot, I'll conduct more thorough local testing and will come back a bit later.

**Comment by rarzumanyan** [comment]
@jakepoz 

The issue was on my side, `git clean -fd` and clean re-install was the key to success.

**Comment by jakepoz** [comment]
Thank you @rarzumanyan

**Pull request merged**
