### PR TITLE
protect cuda context creation from race condition

### PR DESCRIPTION
**Pull request by vtpl1**
Hi @rarzumanyan 
`CudaResMgr` being singleton implementation the  `GetCtx` and `GetStream` needs protection against concurrent call.
Independent mutex lock is provided to protect cuda context and cuda stream.
This is required for multi-threaded operation #182

### CODE REVIEW

**Review by rarzumanyan — DISMISSED** [review]
Hi @vtpl1 

Thanks for the PR!
Please squash commits and cleanup commit message, right now I see 10 commits altogether.
The patch itself LGTM.

**Comment by vtpl1** [comment]
Hi @rarzumanyan,
I am poor at git intrinsic so it would take some time to sqaush.

**Comment by rarzumanyan** [comment]
> 
> 
> Hi @rarzumanyan,
> I am poor at git intrinsic so it would take some time to sqaush.

I can make a commit on my machine and add you as authors (Monotosh Das and Subhasis Chakraborty) if you're ok with it.

**Comment by rarzumanyan** [comment]
> 
> 
> Hi @rarzumanyan,
> I am poor at git intrinsic so it would take some time to sqaush.

Let me check, maybe I can do this on my side with GitHub.

**Comment by vtpl1** [comment]
@rarzumanyan ,
please go ahead with the required commit message, meanwhile let me learn git a bit.

**Pull request merged**
