### PR TITLE
Use sysconfig for getting the python extension suffix

### PR DESCRIPTION
**Pull request by dbermond**
This will hopefully make it work on more systems.

### CODE REVIEW

**Comment by rarzumanyan** [comment]
@dbermond 

Now works both on Windows and Linux, thanks a lot!
Will merge to `master` soon.

**Comment by dbermond** [comment]
Good to know it's working fine. Thank you for merging this! :)

**Comment by rarzumanyan** [comment]
Hi @dbermond 

I had to roll back your PR because of regression issues some VPF users have.
Below is the CMake output:
```
CMake Error at CMakeLists.txt:75 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" (requested
  version 3.4) with any of the following names:

    PythonConfig.cmake
    python-config.cmake

  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by dbermond** [comment]
Probably they are using an old CMake (pre-3.12).

Is this reported somewhere? Could you please provide more details? For example: operating system, command used for building, Python version(s), CMake version, etc.

As you know, this means that users don't have Python properly configured on their machines (or that their CMake is old).

**Comment by rarzumanyan** [comment]
@dbermond 

Will come back with more details a bit later.

If patch requires certain CMake version, please add version requirement to CMake file itself.

Many users don’t have a chance to update CMake at their will so putting this feature under conditional statement may be a good idea as well.

**Comment by dbermond** [comment]
Thank you. Waiting for the details :)

**Pull request merged**
