### PR TITLE
WIP: Filter packets

### PR DESCRIPTION
**Pull request by lferraz**
Added a new class that allows to filter packets (e.g. coming from PyAV).

### CODE REVIEW

**Comment by rarzumanyan** [comment]
Hi @lferraz 

VPF can work with any source of Annex.B Access Units as it's shown [here](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Decoding-video-from-RTSP-camera) without the need to develop a separate class for that.

Is there a particular need to develop a dedicated class which will remux AVPackets to Annex.B Access Units?

**Comment by lferraz** [comment]
Basically to be able to combine PyAV and VPF. With this feature I can read packets with PyAV and decode them with VPF.
As far as I remember this feature is blocked because PyAV needs to add filters in their python API.

**Comment by lferraz** [comment]
@rarzumanyan I did this PR because your comment [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/178#issuecomment-809546304)

**Comment by rarzumanyan** [comment]
@lferraz 

Thanks for detailed description.
I'm still in doubt about this approach mainly because of 2 reasons:

1. `AVPacket` isn't part of "public" FFmpeg API itself. It's neither Annex.B NAL Unit nor Annex.B Access Unit. It's a blob which stores bits & its content and internal format is subject to change without prior notice as long as it doesn't break the FFmpeg API. If this happens I'll have hard time supporting the code in future.
2. I've spend quite a time working on "proper" integration between VPF and PyAV and hosetly I'd rather clone the pending bitstream filters PR and / or contact other PyAV developers to merge exsiting one. Not only VPF will benefit from this but other people as well because it will augment PyAV functionality.

I understand that this PR solves very tangible business issue and makes lots of sense for your VPF application although I'd like to reduce the FFmpeg codebase within VPF as much as possible because 99% time I'm dealing with issues when people struggle to find suitable options to connect to RTSP camera and such which is far outside the video processing scope.

I'm running out of depth in many muxing-related areas (such as proper seek for variable FPS videos, RTSP connection peculiarities etc.) and adjacent areas. One possible approach I see here is to use available OSS projects such as PyAV as much as possible instead of spreading existing development & support resources too thin.

**Comment by lferraz** [comment]
@rarzumanyan I understand perfectly your concerns. No problem.
I think the best approach is to use my own fork of VPF until the PyAV guys merge that branch.
If you are agree with me feel free to close the PR.

Let me repeat myself, thank you so much for your effort and help!!

**Pull request closed without merging**
