### PR TITLE
Support FFMPEG_(LIB,INCLUDE)_DIR vars

### PR DESCRIPTION
**Pull request by ferdnyc**
Many Linux distributions install FFmpeg include files in a path such as `/usr/include/ffmpeg/`, meaning that the existing detection using `${FFMPEG_DIR}` will be unable to find them by looking in `${FFMPEG_DIR}/include`.

This PR adds additional cache variables `${FFMPEG_INCLUDE_DIR}` and `${FFMPEG_LIB_DIR}`, which default to `${FFMPEG_DIR}/include` and `${FFMPEG_DIR}/lib` respectively, but allow the paths to be separately overridden if necessary. The detection of FFmpeg components uses these two variables, instead of `${FFMPEG_DIR}`.

### CODE REVIEW

**Comment by ferdnyc** [comment]
@rarzumanyan 

Hmm, really? How strange. I just tested again (with `-DFFMPEG_DIR=/foo` on the command line), and my cache ended up like this:
```cmake
 FFMPEG_DIR                       /foo                                         
 FFMPEG_INCLUDE_DIR               /foo/include                                 
 FFMPEG_LIB_DIR                   /foo/lib                                     
```

What version of CMake? (I'm running 3.16.)

Also, did you delete `CMakeCache.txt` before running CMake? As things currently stand, because `FFMPEG_LIB_DIR` and `FFMPEG_INCLUDE_DIR` get set as `CACHE` variables in the first run, Setting `FFMPEG_DIR` won't override them in subsequent runs.

I could try to add logic that uses `FFMPEG_LIB_DIR` and `FFMPEG_INCLUDE_DIR` from the cache if they're set, but doesn't _set_ them as `CACHE` variables... that way, they'll only exist in the cache if the user explicitly sets them. That should work for the reconfig case.

**Comment by ferdnyc** [comment]
@rarzumanyan 

OK, I've pushed in commits to set `CACHE` variables for `FFMPEG_LIB_DIR` and `FFMPEG_INCLUDE_DIR` IFF they were supplied by the user; generated paths won't be cached. So, as long as the more-specific variables aren't set, `FFMPEG_DIR` will always override both.

If the user _does_ set e.g. `FFMPEG_INCLUDE_DIR` at some point, then `cmake -DFFMPEG_DIR=/foo` will no longer change `FFMPEG_INCLUDE_DIR`, though it's still possible to reset that:
```sh
$ cmake -UFFMPEG_INCLUDE_DIR -DFFMPEG_DIR=/foo
-- Searching for FFmpeg libs in /foo/lib
-- Searching for FFmpeg headers in /foo/include
-- Configuring done
-- Generating done
-- Build files have been written to: VideoProcessingFramework/build
```

I also added (as you can see) `message(STATUS ...)` lines to display the paths in use during the config run.

I'd encourage you to use a find module for FFmpeg, though, as it offers a lot more flexibility. You can find my [FindFFmpeg.cmake](https://github.com/OpenShot/libopenshot/blob/develop/cmake/Modules/FindFFmpeg.cmake) in the [OpenShot/libopenshot](https://github.com/OpenShot/libopenshot) repo — it accepts `COMPONENT` names for the individual libraries to detect, and creates `IMPORTED TARGET`s for each discovered component. It'll use `pkg-config` to discover the library paths, if available, and the variable `FFMPEGDIR` can be used to set an additional root path for the search.

So, for instance, you could use it like so:
```cmake
# Find the libraries and create targets
find_package(FFmpeg REQUIRED COMPONENTS avcodec avformat avutil)

# Replace BOTH include_directories() and target_link_libraries() with
target_link_libraries(TC PUBLIC FFmpeg::avcodec)
target_link_libraries(TC PUBLIC FFmpeg::avformat)
target_link_libraries(TC PUBLIC FFmpeg::avutil)

# No need (probably) to propagate variables to PARENT_SCOPE
```

The legacy variables `(component)_INCLUDE_DIRS`, `(component)_LIBS`, etc. are set for each component as well, for backwards-compatibility.

**Comment by rarzumanyan** [comment]
Hi Frank,

I can't use [FindFFmpeg.cmake](https://github.com/OpenShot/libopenshot/blob/develop/cmake/Modules/FindFFmpeg.cmake) due to different licensing.
Thanks for the updated CMakeLists.txt version, I've squashed & merged it.

**Comment by ferdnyc** [comment]
@rarzumanyan Understood. BSD 3-clause is how CMake itself is licensed. Find modules nearly all find their inspiration in one or another of the modules in the bundled set that's used as a starting point / template, so they tend to inherit the same licensing.

**Pull request merged**
