### PR TITLE
gpu buffer branch formatting

### PR DESCRIPTION
**Pull request by vtpl1**
@rarzumanyan ,
This PR is for formatting of the changed codes on `on_gpu_buffer` before commiting next PR for actual changes.

For VS code users the following settings are used to do the formatting:

`"C_Cpp.clang_format_fallbackStyle": " { BasedOnStyle: Google, ColumnLimit: 80}"`

Also renamed `PyBufferUploader` to `PyFrameUploaderToCudaBuffer` and changed the function name from `UploadSingleBuffer` to `UploadSingleFrame`

### CODE REVIEW

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

Please don't format source files just because you don't like the style - such patches are nightmare to merge.
If you like to format your patches with Google coding style - I'm OK with that but please keep the amount of changes as small as possible.

I've not forgotten about your PR regarding the coding style and will come back to it bit later as I'm done with `CudaBuffer` PR, and Docker-ization PR.

**Comment by vtpl1** [comment]
>
> 
> Also renamed `PyBufferUploader` to `PyFrameUploaderToCudaBuffer` and changed the function name from `UploadSingleBuffer` to `UploadSingleFrame`

@rarzumanyan ,
What about this rename?

**Comment by vtpl1** [comment]
@rarzumanyan 
,
The formatting was done for the newely introduced code segment of `CudaBuffer` just to make it consistent so that it does not look like a ad-hoc code.

Anyway, your comment about the formatting is taken.

**Comment by rarzumanyan** [comment]
> > Also renamed `PyBufferUploader` to `PyFrameUploaderToCudaBuffer` and changed the function name from `UploadSingleBuffer` to `UploadSingleFrame`
> 
> @rarzumanyan ,
> What about this rename?

IMO proposed names are bit confusing because `PyBufferUploader` just uploads any kind of numpy array to GPU. 
It may be a compressed video bit stream just as well (Nvenc can also output compressed video frames to video memory) or arbitrary data one may want to use to run a custom CUDA kernel over the decoded `Surface`.

**Comment by vtpl1** [comment]
> > > Also renamed `PyBufferUploader` to `PyFrameUploaderToCudaBuffer` and changed the function name from `UploadSingleBuffer` to `UploadSingleFrame`
> > 
> > 
> > @rarzumanyan ,
> > What about this rename?
> 
> IMO proposed names are bit confusing because `PyBufferUploader` just uploads any kind of numpy array to GPU.
> It may be a compressed video bit stream just as well (Nvenc can also output compressed video frames to video memory) or arbitrary data one may want to use to run a custom CUDA kernel over the decoded `Surface`.


@rarzumanyan ,
`PyFrameUploader` is another way to upload numpy array, which with `PyBufferUploader` in my opinion might create confusion.
`Frame` and `Buffer` are interchangeably used for CPU memory.

**Comment by rarzumanyan** [comment]
> > IMO proposed names are bit confusing because `PyBufferUploader` just uploads any kind of numpy array to GPU.
> > It may be a compressed video bit stream just as well (Nvenc can also output compressed video frames to video memory) or arbitrary data one may want to use to run a custom CUDA kernel over the decoded `Surface`.
> 
> @rarzumanyan ,
> `PyFrameUploader` is another way to upload numpy array, which with `PyBufferUploader` in my opinion might create confusion.
> `Frame` and `Buffer` are interchangeably used for CPU memory.

`PyFrameUploader`and `PyBufferUploader` have different names and return different values, IMO it's difficult to confuse them.

**Pull request closed without merging**
