### PR TITLE
Updating Python Samples

### PR DESCRIPTION
**Pull request by sandhawalia**
Hey folks, 

Any thoughts about cleaning up the python example scripts. I'd be up for using

1. [`argparse`](https://docs.python.org/3/library/argparse.html) for command line arg parsing 
2. [`pyblack`](https://pypi.org/project/black/) for linting
3. [`logger`](https://docs.python.org/3/howto/logging.html) instead of `print`
4. [`tqdm`](https://tqdm.github.io) for showing progress + decoding/encoding throughput
5. verbosity arg, `-v` or `--verbose`

i've only modified one file [`SampleDecode.py`](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecode.py) to see if there is interest. I can redo all of the rest if we wanna move forward with it. Here's how to use it from this branch. Follow building docker image from [here](https://github.com/NVIDIA/VideoProcessingFramework#docker-instructions-linux). Then run container.

```
docker-compose -f docker/docker-compose.yml run -v $HOME/Downloads:/Downloads vpf
```

Show Help
```
python SampleDecode.py --help
usage: This sample decodes input video to raw NV12 file on given GPU. [-h] -g GPU_ID -e ENCODED_FILE_PATH -r
                                                                      RAW_FILE_PATH [-v]

optional arguments:
  -h, --help            show this help message and exit
  -g GPU_ID, --gpu-id GPU_ID
                        GPU id, check nvidia-smi
  -e ENCODED_FILE_PATH, --encoded-file-path ENCODED_FILE_PATH
                        Encoded video file (read from)
  -r RAW_FILE_PATH, --raw-file-path RAW_FILE_PATH
                        Raw NV12 video file (write to)
  -v, --verbose         Verbose
```

Run 

```
python SampleDecode.py -g 0 -e /Downloads/bikes.mp4 -r /Downloads/bikes-vpf.mp4
Decoding : : 1130 frames [00:03, 282.19 frames/s
```

PS: Ignore the commit history for now. Needs cleanup.

### CODE REVIEW

**Comment by rarzumanyan** [comment]
Hi @sandhawalia !

>Any thoughts about cleaning up the python example scripts

I'm open to this idea and I'd also like to clean up samples a bit. 

This week the GTC is a top priority, so I'll come back to this PR as soon as conference is over. Also if you don't mind I'll add you to another issue thread where some help is needed to community member who'd like to contribute to one of VPF samples.

P. S.
Please feel free to the attend one of CWE (Connect With Expert) online sessions which are part of GTC ;)

**Comment by sandhawalia** [comment]
Thanks @rarzumanyan! Happy to help on the VPF samples. Looking forward to GTC :).

**Comment by rarzumanyan** [comment]
@sandhawalia 

Could you please rebase your PR?
I've merged latest changes from previous PR and `v_1.1.2` into `master` so now the rebase is needed.

**Comment by sandhawalia** [comment]
Sure. Doing it in a bit

**Comment by sandhawalia** [comment]
Moving https://github.com/NVIDIA/VideoProcessingFramework/pull/314 for clear rabase after `SampleOpenGL.py` updates in `v_1.1.2`

**Pull request closed without merging**
