### PR TITLE
Extract timing information

### PR DESCRIPTION
**Pull request by maxclaey**

### CODE REVIEW

**Comment by maxclaey** [comment]
Thanks a lot for the feedback! However, I'm a bit confused. The reason that `getDecodedSurface` and `getElementaryVideo` are were updated was to be able to get the `packetData` related to the last decoded frame up to the `DecodeSingleSurface` method and save it there. The last saved value could then be returned in the `LastPacketData` call. However, if I update the `LastPacketData` call as you suggest, then I guess the changes to the two other functions are no longer needed?

**Comment by maxclaey** [comment]
I updated it to use the `LastPacketData` as you proposed, and reverted the changes on `getDecodedSurface` and `getElementaryVideo` as they are no longer required. As the demuxer is only executed in `getElementaryVideo`, which is only called when calling `DecodeSingleSurface`, I believe the value that will be retrieved from `LastPacketData` will always be the data from the frame of the last `DecodeSingleSurface` call, which was intended.

**Comment by rarzumanyan** [comment]
@maxclaey 
>However, if I update the LastPacketData call as you suggest, then I guess the changes to the two other functions are no longer needed?

Hm, that's a good point.

In the current design `DemuxFrame` and `NvdecDecodeFrame` are combined together within `PyNvDecoder` class so that demuxing & decoding are done consequently and demuxer's output will not be replaced until next decode call from outside the `PyNvDecoder` class. So effectively there's no need to pass `PacketData` through the function's call stack.

In that case I think `getElementaryVideo` and `getDecodedSurface` functions may be left as they are and 
```cpp
void LastPacketData(PacketData &packetData) const 
{
  auto mp_buffer = (Buffer *)upDemuxer->GetOutput(1U);
  if (mp_buffer) {
    auto mp = mp_buffer->GetDataAs<MuxingParams>();
    packetData = mp->videoContext.packetData;
  }
}
```
may be used.

P. S.
May I ask you about your use scenario? Often people just want to decode video frames from RTSP input, export them to PyTorch tensor and feed to NN. It's a bit rare request to get underlying timing info :)

**Comment by maxclaey** [comment]
Ok, in that case I think we are aligned and my latest changes match your suggestions. What use-case is concerned: for some cases like tracking, it is interesting to know at least the time delta between frames. As this framework basically wraps around ffmpeg, which has this information available, I think it's a good idea to make it accessible, for sure as in hindsight the changes are minimal and it doesn't impact normal behaviour :)

**Comment by rarzumanyan** [comment]
@maxclaey 
Thanks for the update, I can compile and run it without any issues.
However, if I extract the `PacketData` and call corresp. method from Python, I see that some structure fields have garbage values:

```python
def decode(gpuID, encFilePath, decFilePath):
    decFile = open(decFilePath, "wb")
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)

    #Amount of memory in RAM we need to store decoded frame
    frameSize = nvDec.Framesize()
    rawFrameNV12 = np.ndarray(shape=(frameSize), dtype=np.uint8)

    while True:
        try:
            success = nvDec.DecodeSingleFrame(rawFrameNV12)
            if not (success):
                print('No more video frames.')
                break

            data = nvc.PacketData()
            nvDec.LastPacketData(data)
            print('pts:      ', data.pts)
            print('dts:      ', data.dts)
            print('pos:      ', data.pos)
            print('duration: ', data.duration)
    
            bits = bytearray(rawFrameNV12)
            decFile.write(bits)

        except nvc.HwResetException:
            print('Continue after HW decoder was reset')
            continue
```

outputs into console:
```cmd
This sample decodes input video to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Decoding on GPU 0
[h264 @ 000001ac0b1eddc0] Stream #0: not enough frames to estimate rate; consider increasing probesize
pts:       -9223372036854775808
dts:       -9223372036854775808
pos:       786
duration:  40000
pts:       -9223372036854775808
dts:       -9223372036854775808
pos:       28753
duration:  40000
pts:       -9223372036854775808
dts:       -9223372036854775808
pos:       50085
duration:  40000
```
So `pts` and `dts` fields have to be either non-visible from Python or set to proper values after the decode call.

**Comment by maxclaey** [comment]
I just tried to duplicate your example by updating SampleDecode, and for me I get relevant data for pts, dts and duration. I tried both with an rtsp stream (rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream) and a local video file. For the local video file I get relevant data for pos as well, for rtsp I don't (which could make sense?). See output for rtsp stream below.
```This sample decodes input video to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Decoding on GPU 0
pts:       62910
dts:       62910
pos:       18446744073709551615
duration:  1501
pts:       64440
dts:       64440
pos:       18446744073709551615
duration:  1501
pts:       65880
dts:       65880
pos:       18446744073709551615
duration:  1501
pts:       67410
dts:       67410
pos:       18446744073709551615
duration:  1501
pts:       68940
dts:       68940
pos:       18446744073709551615
duration:  1501```
The muxingparams output gets set in `DemuxFrame::Execute()` in TC Tasks.cpp. Maybe the information is not available there in some cases?

**Comment by rarzumanyan** [comment]
@maxclaey 
I was launching the sample with elementary .h264 file as input.
In case the RTSP stream is used the pts and dts info is indeed good.
Merging to master.

**Pull request merged**
